name: 'Hello World'
description: 'Fetch secrets from hashicorp vault'
inputs:
  vault_url:
    description: 'VAULT url/endpoint'
    required: true
  project:
    description: 'Project Name'
    required: true
  environment:
    description: 'Environment Name'
    required: true
  secrets:
    description: 'Secrets name'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.vault_url }}
    - ${{ inputs.project }}
    - ${{ inputs.environment }}
    - ${{ inputs.secrets }}
