# on: [push]

# jobs:
#   hello_world_job:
#     runs-on: ubuntu-latest
#     name: A job to say hello
    
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       - name: Fetch vault secrts
#         id: hello
#         uses: ./
#         with:
#           vault_url: "https://vault.staging-internal.opn.dev"
#           project: "opn-internal"
#           environment: "staging"
#           secrets: | 
#             OPN_INTERNAL_STAGING_AWS_ACCOUNT_ID
#             TEST

#       - name: Get Secret
#         run: |
#           echo "The secret output: ${{ steps.hello.outputs.OPN_INTERNAL_STAGING_AWS_ACCOUNT_ID }}"
#           echo "The test secret: ${{ steps.hello.outputs.TEST }}"
